      # Default values for the generator
      # this file can be used as a template for a custom configuration
      # or to know about the different variables available for the generator
      platys:
          platform-name: 'default'
          platform-stack: 'trivadis/platys-modern-data-platform'
          platform-stack-version: '1.8.0-preview'
          structure: 'flat'
      # ===== Global configuation, valid for all or a group of services ========
      # Timezone, use a Linux string such as Europe/Zurich or America/New_York
      use_timezone: ''
      # the name of the repository to use for private images, which are not on docker hub (currently only Oracle images)
      private_docker_repository_name: 'trivadis'
      
      PROVISIONING_DATA_enable: false
      
      KAFKA_enable: true
      KAFKA_broker_nodes: 3
      KAFKA_delete_topic_enable: true
      KAFKA_auto_create_topics_enable: false

      #kafka schema registry
      KAFKA_SCHEMA_REGISTRY_enable: true
      KAFKA_SCHEMA_REGISTRY_nodes: 1
      KAFKA_SCHEMA_REGISTRY_use_zookeeper_election: false
      KAFKA_SCHEMA_REGISTRY_replication_factor: 1

      #kafka connect
      KAFKA_CONNECT_enable: true
      KAFKA_CONNECT_nodes: 2
      KAFKA_CONNECT_connectors: 'jcustenborder/kafka-connect-twitter:0.3.33'

      #ksqldb
      KAFKA_KSQLDB_enable: true
      KAFKA_KSQLDB_edition: 'oss'
      KAFKA_KSQLDB_nodes: 1

      KAFKA_SCHEMA_REGISTRY_UI_enable: true
      KAFKA_CONNECT_UI_enable: true

      KAFKACAT_enable: true
      KAFKA_AKHQ_enable: true

      # ===== Spark ========
      SPARK_enable: true
      SPARK_version: 2.4.5-hadoop2.8
      SPARK_workers: 2
      SPARK_jars_packages: 'org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.5'
      #SPARK_jars_packages: 'org.apache.spark:spark-sql-kafka-0-10_2.12:3.0.0'
      SPARK_jars_excludes: ''

      SPARK_HISTORY_enable: true

      # ===== Apache Hive Metastore ========
      HIVE_METASTORE_enable: true

      # =====  Streamsets and stremsets edge ========
      STREAMSETS_enable: true

      # ===== Zeppelin ========
      ZEPPELIN_enable: true
      ZEPPELIN_version: 0.8.2-spark2.4-hadoop2.8

      # ===== RDBMS ========
      POSTGRESQL_enable: true
      POSTGRESQL_user: demo
   
      # ===== Presto ========
      PRESTO_enable: true
      PRESTO_edition: 'starburstdata'

      # ===== Dremio ========
      DREMIO_enable: true

      # ===== Apache Drill ========
      DRILL_enable: true

      #=====  MinIO Object Storage ========
      MINIO_enable: true
      AWSCLI_enable: true

      